package main

import (
	"bufio"
	"fmt"
	"go/ast"
	"go/token"
	"log"
	"os"
	"regexp"
	"strings"
)

type ReplaceConfig struct {
	Filename    string
	Start       int
	End         int
	CurrentType string
	ReplaceType string
}

func ScanFunction(config ReplaceConfig) {
	lines := ReadFileLines(config.Filename, config.Start, config.End)
	line := ReplaceFuncType(lines, config.ReplaceType)
	WriteResultToFile(line)
}

func ReadFileLines(filename string, start int, end int) []string {
	f, err := os.Open(filename)
	if err != nil {
		log.Println("err", err)
	}
	scanner := bufio.NewScanner(f)
	var lines []string
	lineNumber := 1
	for scanner.Scan() {
		line := scanner.Text()
		if lineNumber >= start && lineNumber <= end {
			lines = append(lines, line)
		}
		lineNumber++
	}
	return lines
}

func ReplaceFuncType(lines []string, replaceType string) string {
	file := strings.Join(lines, "\n")
	replacements := map[string]string{
		replaceType:                  "Model",
		strings.ToLower(replaceType): "model",
	}

	for key, value := range replacements {
		r := regexp.MustCompile(`[ ()";{}\n\t]` + key + `[ ()";{}\n\t]`)
		r2 := regexp.MustCompile(key)

		file = r.ReplaceAllStringFunc(file, func(match string) string {
			return r2.ReplaceAllString(match, value)
		})
	}

	return file
}

func WriteResultToFile(line string) {
	f, err := os.Create(Conf.Output + "_lazygen.txt")
	if err != nil {
		log.Println(err)
	}
	defer f.Close()
	f.Write([]byte("// ATTENTION! THIS FILE WAS GENERATED BY LAZYGEN\n"))
	f.Write([]byte("// DONT TOUCH IT...\n"))
	f.Write([]byte("package " + Conf.Package + "\n"))
	f.Write([]byte("\n"))
	f.Write([]byte(line))
}

type CommentConf struct {
	Text     string
	Filename string
	Pos      int
}

func FindValidFunction(fs *token.FileSet, comment *ast.Comment) (bool, token.Position) {
	r := regexp.MustCompile("lazygen")
	if r.Match([]byte(comment.Text)) {
		fmt.Println("Func is valid")
		return true, fs.Position(comment.Pos())
	}
	return false, token.Position{}
}
